export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_LOADING = 'FETCH_USERS_LOADING';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';

export const FETCH_FRIENDS_LOCATION = 'FETCH_FRIENDS_LOCATION';
export const FETCH_USER_LOCATIONS = 'FETCH_USER_LOCATIONS';
export const CLEAR_USER_LOCATIONS = 'CLEAR_USER_LOCATIONS';